# Generated by Django 3.2 on 2021-05-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawlid', models.CharField(blank=True, max_length=50, null=True)),
                ('containerid', models.IntegerField()),
                ('url', models.URLField()),
                ('urlid', models.CharField(blank=True, max_length=300, null=True)),
                ('ready', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
