# Generated by Django 3.2 on 2021-05-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrasync', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlstate',
            name='containerid',
        ),
        migrations.AlterField(
            model_name='crawlstate',
            name='crawlid',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='crawlstate',
            name='urlid',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
